profile: null
region: ap-northeast-1
versioning: false
default_alias: master
configuration:
  name: kipi-geko-message
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: message.lambda_handler
  description: Kipi LINE Bot
  timeout: 10
  memory_size: 128
